name: Epitech-Mirror

on:
  push:
    branches:
      - main
      - dev
env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-CPP-500-PAR-5-2-rtype-arthur.aillet.git

jobs:
 push-to-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cloning to mirror

        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
