on:
  workflow_dispatch:

name: Create Release Major Asset

jobs:
  build:
    name: Upload Release Asset
    permissions:
      contents: write
      # write permission is required for autolabeler
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: cmake -DTESTS=on -S . -B ./build

# ==============================
      - name: Create Release
        id: create_release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-major.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
