name: units-tests

on:
  push:
    branches:
      - "dev"
      - "feat/CI/CD"

jobs:
  test:
    # runs-on: [ubuntu-latest, windows-latest]
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - run: sudo apt install libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev
      - run: sudo apt install libglfw3-dev
      - run: sudo apt install libcriterion-dev
      - name: Build
        run: cmake -DTESTS=on -S . -B ./build
      - name: Test
        run: make --no-print-directory -C build tests-run
      - name: format
        run: make format