name: units-tests

on:
  push:
    branches:
      - "dev"
      - "feat/CI/CD"

jobs:
  test:
    # runs-on: [ubuntu-latest, windows-latest]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev
      - run: sudo apt install libglfw3-dev
      - run: sudo apt install libcriterion-dev
      - name: Build
        run: cmake -DTESTS=on -S . -B ./build
      - name: Test
        run: make -j --no-print-directory -C build tests-run-cevy
      # - name: format
      #   run: 